# Generated by Django 5.1.3 on 2024-12-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id_exam', models.AutoField(primary_key=True, serialize=False)),
                ('date_hour', models.DateTimeField()),
                ('place', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
    ]
