# Generated by Django 5.1.4 on 2025-02-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_group_admin'),
        ('exam', '0002_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Group.group'),
        ),
    ]
