# Generated by Django 5.1.4 on 2025-02-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0007_alter_group_admin'),
        ('Teachers', '0002_teacher_admin'),
        ('exam', '0003_exam_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Group.group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Teachers.teacher'),
        ),
    ]
