# Generated by Django 5.1.3 on 2025-02-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_admin_fullname_admin_admin_fullname_and_more'),
        ('Scores', '0001_initial'),
        ('Teachers', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scores', to='Admin.admin'),
        ),
        migrations.AddField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='score',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_added', to='Teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='score',
            name='note',
            field=models.FloatField(),
        ),
    ]
