# Generated by Django 5.1.4 on 2024-12-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='note',
            field=models.FloatField(),
        ),
    ]
