# Generated by Django 5.1.4 on 2025-02-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0002_alter_score_note'),
        ('Scores', '0002_score_admin_alter_score_note'),
    ]

    operations = [
    ]
