# Generated by Django 5.1.3 on 2025-02-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0002_score_admin_score_created_at_score_exam_and_more'),
        ('Scores', '0003_merge_20250205_2055'),
    ]

    operations = [
    ]
