# Generated by Django 5.1.3 on 2025-02-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_admin_fullname'),
        ('Scores', '0004_merge_20250213_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Admin.admin'),
        ),
    ]
