# Generated by Django 5.1.4 on 2025-02-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_admin_fullname'),
        ('Scores', '0004_merge_20250225_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Admin.admin'),
        ),
    ]
