# Generated by Django 5.1.3 on 2024-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('fullname_admin', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date_of_inscription', models.DateField()),
            ],
        ),
    ]
