# Generated by Django 4.2.7 on 2025-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('date_of_inscription', models.DateField()),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
