# Generated by Django 5.1.3 on 2024-12-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='fullname_admin',
        ),
        migrations.AddField(
            model_name='admin',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
    ]
