# Generated by Django 5.1.4 on 2025-02-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_admin_fullname_admin_admin_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
