# Generated by Django 4.2.7 on 2025-05-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers', '0001_initial'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year_of_creation', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Admin.admin')),
                ('teacher', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Teachers.teacher')),
            ],
        ),
    ]
