# Generated by Django 5.1.4 on 2024-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_creation', models.PositiveIntegerField()),
            ],
        ),
    ]
