# Generated by Django 5.1.4 on 2024-12-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_admin_fullname_admin_admin_fullname_and_more'),
        ('Group', '0002_group_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Admin.admin'),
            preserve_default=False,
        ),
    ]
