# Generated by Django 5.1.4 on 2025-02-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_group_admin'),
        ('Group', '0005_group_name'),
    ]

    operations = [
    ]
