# Generated by Django 4.2.7 on 2025-05-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=255)),
                ('date_of_inscription', models.DateField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='Admin.admin')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
