# Generated by Django 5.1.3 on 2024-12-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=255)),
                ('date_of_inscription', models.DateField()),
            ],
        ),
    ]
