# Generated by Django 5.1.4 on 2025-04-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_teacher_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
