# Generated by Django 5.1.4 on 2025-05-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_admin_fullname'),
        ('Teachers', '0003_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='Admin.admin'),
        ),
    ]
