# Generated by Django 5.1.3 on 2025-02-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
