# Generated by Django 5.1.4 on 2024-12-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_admin_fullname_admin_admin_fullname_and_more'),
        ('student', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Admin.admin'),
            preserve_default=False,
        ),
    ]
