# Generated by Django 5.1.4 on 2025-01-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_remove_group_students_group_teacher'),
        ('student', '0003_student_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Group.group'),
            preserve_default=False,
        ),
    ]
